### ISSUE TITLE
Add logging to library or throw exception

### ISSUE THREAD

**Issue by martinalig** [ElectronicChartCentre/java-vector-tile#35]
Hi

We have been using the library to generate tiles since last year. Since a few weeks we have been trying to fix a bug in the generated tiles.
In the end, we found out, that the supplied geometries where not valid in some cases.
This resulted in situations, where the polygons where not clipped anymore and therefore the generated vector tile was not fully valid anymore.

The corresponding code is here: https://github.com/ElectronicChartCentre/java-vector-tile/blob/master/src/main/java/no/ecc/vectortile/VectorTileEncoder.java#L253:L274

As the exceptions are just silently ignored and no message is printed, it is quite hard to see this problem.

Do you have any opinions in adding logging or maybe rethink the exception handing?

**Comment by halset** [comment]
Thanks for the feed-back. Ignored messages are not good when debugging, but throwing an exception for a single failed geometry will probably lead to a lot of failed tiled. And logging might be a bit busy. Perhaps using java build in Logger and use a proper log level for it could be a good option?

We had an issue with some polygons that turned out to be invalid after simplification. To fix this, we ended up trying to decode the generated geometry and check the validity. Might not be relevant for you, but you can see that in https://github.com/ElectronicChartCentre/java-vector-tile/commit/48474169b9814bf74cda7525b274c0050ef55acb
